model = "gpt-5.3-codex"
model_reasoning_effort = "medium"
[projects."/home/vmenge/dev/tfh/orb-software"]
trust_level = "untrusted"

[projects."/home/vmenge/nixos"]
trust_level = "trusted"

[projects."/home/vmenge/dev/sucata"]
trust_level = "untrusted"

[projects."/home/vmenge/.codex"]
trust_level = "trusted"
