background {
  monitor =
  path = screenshot
  blur_passes = 3
  blur_size = 4
  brightness = 0.7
}

input-field {
  monitor =
  size = 200, 50
  outline_thickness = 1
  outer_color = rgb(000000)
  inner_color = rgba(000000BB)
  font_color = rgb(ffffff)
  check_color = rgb(ffffff)
  fail_color = rgb(ff0000)
  fail_text = $FAIL ($ATTEMPTS)
  rounding = 10
  fade_on_empty = true
  placeholder_text =
  position = 0, -80
  halign = center
  valign = center
}

label {
  monitor =
  text = cmd[update:1000] echo "$TIME"
  color = rgba(ffffffff)
  font_size = 55
  font_family = DepartureMono Nerd Font
  position = 0, 80
  halign = center
  valign = center
}
