return {
	-- "epwalsh/obsidian.nvim",
	-- version = "*", -- recommended, use latest release instead of latest commit
	-- lazy = true,
	-- event = {
	-- 	-- If you want to use the home shortcut '~' here you need to call 'vim.fn.expand'.
	-- 	-- E.g. "BufReadPre " .. vim.fn.expand "~" .. "/my-vault/**.md"
	-- 	"BufReadPre /home/vmenge/brain/**.md",
	-- 	"BufNewFile /home/vmenge/brain/**.md",
	-- },
	-- dependencies = {
	-- 	-- Required.
	-- 	"nvim-lua/plenary.nvim",
	-- },
	-- opts = {
	-- 	workspaces = {
	-- 		{
	-- 			name = "personal",
	-- 			path = "/home/vmenge/brain",
	-- 		},
	-- 		{
	-- 			name = "work",
	-- 			path = "/home/vmenge/brain",
	-- 		},
	-- 	},
	--
	-- 	ui = {
	-- 		enable = true, -- set to false to disable all additional syntax features
	-- 		update_debounce = 200, -- update delay after a text change (in milliseconds)
	-- 		-- Define how various check-boxes are displayed
	-- 		checkboxes = {
	-- 			-- NOTE: the 'char' value has to be a single character, and the highlight groups are defined below.
	-- 			[" "] = { char = "󰄱", hl_group = "ObsidianTodo" },
	-- 			["x"] = { char = "", hl_group = "ObsidianDone" },
	-- 			[">"] = { char = "", hl_group = "ObsidianRightArrow" },
	-- 			["~"] = { char = "󰰱", hl_group = "ObsidianTilde" },
	-- 			-- Replace the above with this if you don't have a patched font:
	-- 			-- [" "] = { char = "☐", hl_group = "ObsidianTodo" },
	-- 			-- ["x"] = { char = "✔", hl_group = "ObsidianDone" },
	--
	-- 			-- You can also add more custom ones...
	-- 		},
	-- 	},
	--
	-- 	-- Optional, by default when you use `:ObsidianFollowLink` on a link to an external
	-- 	-- URL it will be ignored but you can customize this behavior here.
	-- 	---@param url string
	-- 	follow_url_func = function(url)
	-- 		-- Open the URL in the default web browser.
	-- 		-- vim.fn.jobstart({ "open", url }) -- Mac OS
	-- 		vim.fn.jobstart({ "xdg-open", url }) -- linux
	-- 	end,
	-- },
}
