return {
  {
    "nvim-treesitter/nvim-treesitter",
    branch = "main",
    build = ":TSUpdate",
    dependencies = {
      { "nvim-treesitter/nvim-treesitter-textobjects", branch = "main" },
    },
    lazy = false,
    priority = 1,
    opts = {
      ensure_installed = {
        "asm",
        "bash",
        "c",
        "c_sharp",
        "clojure",
        "cmake",
        "comment",
        "cpp",
        "css",
        "csv",
        "dart",
        "dockerfile",
        "elixir",
        "elm",
        "erlang",
        "gdscript",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "gleam",
        "glsl",
        "go",
        "graphql",
        "hjson",
        "hlsl",
        "hocon",
        "html",
        "http",
        "ini",
        "java",
        "javascript",
        "jq",
        "jsdoc",
        "json",
        "json5",
        "kotlin",
        "lua",
        "luadoc",
        "luap",
        "make",
        "markdown",
        "markdown_inline",
        "nix",
        "nu",
        "ocaml",
        "ocaml_interface",
        "prisma",
        "python",
        "query",
        "r",
        "regex",
        "roc",
        "ruby",
        "rust",
        "scala",
        "scss",
        "sql",
        "svelte",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "vimdoc",
        "xml",
        "yaml",
        "zig",
      },
    },

    config = function(_, opts)
      local ts = require("nvim-treesitter")
      ts.setup()

      vim.api.nvim_create_autocmd("FileType", {
        group = vim.api.nvim_create_augroup("vmenge-treesitter", { clear = true }),
        callback = function(args)
          if pcall(vim.treesitter.start, args.buf) then
            vim.bo[args.buf].indentexpr = "v:lua.require'nvim-treesitter'.indentexpr()"
          end
        end,
      })
    end,
  },
  {
    "nvim-treesitter/nvim-treesitter-context",
    opts = {
      max_lines = 2,
      multiline_threshold = 2,
      trim_scope = "inner",
    },
  },
}
